ES_Software/ES_Software/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace ES_Software.Controllers
{
    public class AdminController : Controller
    {
        public static string cliente = "";

        static string recurso = "";

        public static string Recurso { get => recurso; set => recurso = value; }

        public ActionResult AdminRegistro()
        {
            return View();
        }
        public ActionResult AdminPaquetes()
        {
            return View();
        }
        public ActionResult AdminRecursos()
        {
            return View();
        }
        public ActionResult AdminHistorial()
        {
            return View();  
        }
        
        public ActionResult AdminIngresarRecurso(ES_Software.Models.AdminModelRecursos model)
        {
            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("RegistrarRecurso", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.Add("@tipoRecurso", System.Data.SqlDbType.VarChar, 50).Value = model.tipoRecurso.ToString();
            cmd.Parameters.Add("@nombre", System.Data.SqlDbType.VarChar, 50).Value = model.nombreRecurso.ToString();
            cmd.Parameters.Add("@telefono", System.Data.SqlDbType.BigInt).Value = Int32.Parse(model.telefono.ToString());
            cmd.Parameters.Add("@correo", System.Data.SqlDbType.VarChar,50).Value = model.correo.ToString();
            cmd.Parameters.Add("@provincia", System.Data.SqlDbType.VarChar, 50).Value = model.provincia.ToString();

            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }
            return View("AdminRecursos");
        }
        public ActionResult AdminEditarRecurso()
        {
            return View();
        }

        public ActionResult AdminEditarPaquete()
        {
            return View("AdminPaquetes");
        }





        [HttpPost]
        public ActionResult AdminRegistroAdministrador(ES_Software.Models.AdminRegistrarAdministrador model, string returnUrl)
        {

            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("RegistrarAdministrador", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.Add("@nombre", System.Data.SqlDbType.VarChar, 50).Value = model.Nombre.ToString();
            cmd.Parameters.Add("@codigoEmpleado", System.Data.SqlDbType.VarChar, 50).Value = model.IDEmpleado.ToString();
            cmd.Parameters.Add("@usuario", System.Data.SqlDbType.VarChar, 50).Value = model.Usuario.ToString();
            cmd.Parameters.Add("@clave", System.Data.SqlDbType.VarChar, 50).Value = model.Contrasena.ToString();
            cmd.Parameters.Add("@cedula", System.Data.SqlDbType.BigInt).Value = Int32.Parse(model.Cedula.ToString());
            cmd.Parameters.Add("@telefono", System.Data.SqlDbType.BigInt).Value = 55555;
            cmd.Parameters.Add("@direccion", System.Data.SqlDbType.VarChar,50).Value = "-------";
            cmd.Parameters.Add("@correo", System.Data.SqlDbType.VarChar, 50).Value = model.Correo.ToString();


            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }
            return View("AdminRegistroAdministradores");
        }

        public ActionResult AdminRegistroAdministradores()
        {

            return View();
        }


        public ActionResult EliminarRecurso(string returnUrl, string nombreRecurso)
        {

            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("EliminarRecurso", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.Add("@nombre", System.Data.SqlDbType.VarChar, 50).Value = nombreRecurso;

            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }
            return View("AdminRecursos");

        }

        public ActionResult AdminIngresarPaquete (ES_Software.Models.AdminModelPaquetes model, IList<string> MyCheckboxes)
        {
            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("RegistrarPaquete", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.Add("@nombre", System.Data.SqlDbType.VarChar, 50).Value = model.nombrePaquete.ToString();
            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }

            if (MyCheckboxes != null)
            {



                for (int i = 0; i < MyCheckboxes.Count(); i++)
                { 
                    SqlConnection conexion2 = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
                    SqlCommand cmd2 = new SqlCommand("AgregarProductosPaquete", conexion2);
                    cmd2.CommandType = CommandType.StoredProcedure;
                    cmd2.Parameters.Add("@nombrePaquete", System.Data.SqlDbType.VarChar, 50).Value = model.nombrePaquete.ToString();
                    cmd2.Parameters.Add("@NombreProducto", System.Data.SqlDbType.VarChar, 50).Value = MyCheckboxes[i].ToString();
                    try
                    {
                        conexion2.Open();
                        cmd2.ExecuteNonQuery();

                    }
                    catch (Exception e)
                    {
                        throw e;
                    }
                    finally
                    {
                        conexion2.Close();
                        conexion2.Dispose();
                    }
                }
            }
            
            return View("AdminPaquetes");
        }

        public ActionResult EliminarPaquete(string returnUrl, string id)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View("AdminPaquetes");
        }
        public ActionResult AdminProductos()
        {
            return View();
        }

        public ActionResult AdminIngresarProducto(ES_Software.Models.AdminProductosModel model, IList<string> MyCheckboxes)
        {
            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("RegistrarProducto", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.Add("@idRecurso", System.Data.SqlDbType.VarChar, 50).Value = MyCheckboxes[0].ToString();
            cmd.Parameters.Add("@nombre", System.Data.SqlDbType.VarChar, 50).Value = model.Nombre.ToString();
            cmd.Parameters.Add("@disponible", System.Data.SqlDbType.Int).Value = int.Parse(model.Disponible.ToString());
            cmd.Parameters.Add("@precio", System.Data.SqlDbType.Money).Value = int.Parse(model.Precio.ToString());

            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }
            return View("AdminProductos");
        }

        [HttpPost]
        public ActionResult AdminModificarRecurso(ES_Software.Models.AdminModelRecursos model, string returnUrl)
        {

            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("ModificarRecurso", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.Parameters.Add("@nombre", System.Data.SqlDbType.VarChar, 50).Value = recurso;
            cmd.Parameters.Add("@telefono", System.Data.SqlDbType.BigInt).Value = Int32.Parse(model.telefono.ToString());
            cmd.Parameters.Add("@correo", System.Data.SqlDbType.VarChar, 50).Value = model.correo.ToString();
            cmd.Parameters.Add("@provincia", System.Data.SqlDbType.VarChar, 50).Value = model.provincia.ToString();

            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }
            return View("AdminRecursos");
        }
        public ActionResult EditarRecurso(ES_Software.Models.AdminModelRecursos model, string id)
        {

            recurso = id;

ES_Software/ES_Software/Controllers/ClientController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Outlook = Microsoft.Office.Interop.Outlook;

namespace ES_Software.Controllers
{
    public class ClientController : Controller
    {
       
        static string paqueteActual = "";

        public static string Paquete { get => paqueteActual; set => paqueteActual = value; }

        static string reservacionActual = "";

        public static string ReservacionActual { get => reservacionActual; set => reservacionActual = value; }

        public ActionResult Historial()
        {
            return View();
        }

        public void sendNotificationEmail()
        {

        }
        
        public ActionResult Editar(string returnUrl, string id)
        {

            return View("Historial");

        }
        public ActionResult EnviarCorreo(string returnUrl,string id)
        {
            ViewBag.ReturnUrl = returnUrl;
            var sClient = new SmtpClient("smtp-mail.outlook.com");
            var message = new System.Net.Mail.MailMessage();

            sClient.Port = 587;
            sClient.Host = "smtp.office365.com";
            sClient.EnableSsl = true;
            sClient.UseDefaultCredentials = false;
            sClient.EnableSsl = false;
            sClient.Credentials = new NetworkCredential("es.eventos.rs@outlook.com", "Eseventos");
            sClient.UseDefaultCredentials = false;

            message.Body = "Test";
            message.From = new MailAddress("es.eventos.rs@outlook.com");
            message.Subject = "Test";
            message.CC.Add(new MailAddress("ibarqueroga@gmail.com"));

            sClient.Send(message);


            return View("Reservar");
        }

        [AllowAnonymous]
        public ActionResult Reservar(string returnUrl, string id)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();  

        }
        public ActionResult ReservarPaquete(ES_Software.Models.ClientReservar model, IList<string> MyCheckboxes)
        {
            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("RealizarReservacion", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            string usuario= ES_Software.Controllers.AccountController.Usario_ctivo; ;
            cmd.Parameters.Add("@nombreCliente", System.Data.SqlDbType.VarChar, 50).Value = usuario;
            cmd.Parameters.Add("@paquete", System.Data.SqlDbType.Int).Value = int.Parse(MyCheckboxes[0]);
            cmd.Parameters.Add("@fecha", System.Data.SqlDbType.VarChar,50).Value = model.Fecha.ToString();
            cmd.Parameters.Add("@hora", System.Data.SqlDbType.VarChar,50).Value = model.Hora.ToString();   


            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }
            return View("Reservar");
        }

        public ActionResult MostrarDetalles(string returnUrl, string paquete)
        {
            paqueteActual = paquete;
            return View();
        }
        
        public ActionResult ModificarReservaciones(string returnUrl, string id)
        {
            reservacionActual = id;
            return View("ModificarReservacion");

        }
        [HttpPost]
        public ActionResult ModificarReservacion(ES_Software.Models.ClientReservar model)
        {
            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("ModificarReservacion", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            string usuario = ES_Software.Controllers.AccountController.Usario_ctivo; ;
            cmd.Parameters.Add("@nombreCliente", System.Data.SqlDbType.VarChar, 50).Value = usuario;
            cmd.Parameters.Add("@numeroReservacion", System.Data.SqlDbType.Int).Value = int.Parse(reservacionActual);
            cmd.Parameters.Add("@fecha", System.Data.SqlDbType.VarChar, 50).Value = model.Fecha.ToString();
            cmd.Parameters.Add("@hora", System.Data.SqlDbType.VarChar, 50).Value = model.Hora.ToString();

            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }
            return View("Historial");

        }
        public ActionResult EliminarReservacion(string returnUrl, string id)
        {
            SqlConnection conexion = new SqlConnection("Data Source=DESKTOP-2OQBEMO;Initial Catalog=ESSoftware;Integrated Security=True");
            SqlCommand cmd = new SqlCommand("EliminarReservacion", conexion);
            cmd.CommandType = CommandType.StoredProcedure;
            string usuario = ES_Software.Controllers.AccountController.Usario_ctivo; ;
            cmd.Parameters.Add("@nombreCliente", System.Data.SqlDbType.VarChar, 50).Value = usuario;
            cmd.Parameters.Add("@numeroReservacion", System.Data.SqlDbType.Int).Value = int.Parse(id);

            try
            {
                conexion.Open();
                cmd.ExecuteNonQuery();

            }
            catch (Exception e)
            {
                throw e;
            }
            finally
            {
                conexion.Close();
                conexion.Dispose();
            }
            return View("Historial");

        }


    }
}

ES_Software/ES_Software/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ES Software", "Historial", "Client", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Historial", "AdminHistorial", "Admin")</li>
                    <li>@Html.ActionLink("Recursos", "AdminRecursos", "Admin")</li>
                    <li>@Html.ActionLink("Paquetes", "AdminPaquetes", "Admin")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ignacio Barquero - Andrés Miranda</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ES_Software/ES_Software/Views/Shared/_ClientLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ES Software", "Historial", "Client", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Historial", "Historial", "Client")</li>
                    <li>@Html.ActionLink("Paquetes", "Reservar", "Client")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ignacio Barquero - Andrés Miranda</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ES_Software/ES_Software/Views/Shared/_DetallesLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ES Software", "Historial", "Client", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ignacio Barquero - Andrés Miranda</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ES_Software/ES_Software/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ES Software", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ES_Software/ES_Software/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ES Software", "Login", "Account", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Ignacio Barquero, Andrés Miranda</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>